spring:
  application:
    name: ArrCore
  r2dbc:
    url: r2dbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:arrcore}
    username: ${DB_USER:myuser}
    password: ${DB_PASSWORD:secret}
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
  config:
    import: optional:file:.env[.properties]
  docker:
    compose:
      enabled: false

settings:
  encryption-key: ${SETTINGS_MASTER_KEY:ArrCore_Default_Key_Change_Me!}
